main: com.legendsofvaleros.LegendsOfValeros
name: "${project.name}"
version: "${project.version}"
author: "Crystall, Stumblinbear, Brutus"
depend: [Citizens, Robert, ArmorEquipEvent]

permissions:
    characters.slots.x:
        description: Defines how many character slots a player has.
        default: false

commands:
    suicide:
        description: Commit seppuku.
    pvpdebug:
        description: PvP debug stuff