# ================================================================
# Database instances. See examples for how to configure. 
# Once configured and a connection is successfully established, 
# clients can get connections to the given database through DBPools' API.
# 
# Cannot have two connections to the same instance.
# 
# Currently supported instance types:
# - mysql
# ================================================================

# The connection pools that DBPools will attempt to make when it enables.
connection-pools:
    # The id of the connection pool. This is what is used to access it through the DBPools API.
    mysql1:
        # The type of connection. 
        type: "mysql"
        # The ip/url and port of the database. Do not include driver or database names.
        url: "149.56.29.9:3306"
        # For mysql connections, the name of the database to use.
        database: "lovminecraft"
        # The username to authenticate with.
        user: "lov"
        # The password to authenticate with, if any.
        password: "aD51McCVGaN25caXnG"
        # The maximum amount of connections to this database that can be in use at any time. 
        # If you dont know what to use, just use 1. 
        #
        # A higher number allows for more concurrent operations at once, when they are demanded. 
        # However, unless this is necessary, it is often better to take a very small performance hit 
        # in concurrent database operations for the sake of not overloading the database, which may 
        # result in connections failing altogether. This is especially true for small server 
        # instances which will have less than ~25-50 players, which very likely will not need 
        # multiple connections to avoid long delays, so long as operations are not run on the main thread.
        max-connection-pool-size: 4
