creation-start-text:
- "MSG:You awake suddenly to the sound of horses and people shouting. It seems your comfortable journey came to an abrupt end."
- WAIT:60
- "silverpine-carriage:Blast! I told you fools to take care of the horses, not to let them run away!"
- WAIT:80
- "silverpine-escort: I'm so sorry boss, I'll go fetch them right away."
- WAIT:35
- "silverpine-carriage: Then be quick about it you slacker, before they run all the way back to the docks!"
- WAIT:55
- "silverpine-carriage: Apologies traveller, but you will have to go to Silverpine Castle on foot. It is not far though, just head west down the hill until you reach the stairs."

creation-create-npc: silverpine-bridge-guard
creation-create-text:
- silverpine-bridge-guard:Halt!
- WAIT:15
- silverpine-bridge-guard:No one is allowed to cross this bridge without some proper identification. Hand over your papers.
- WAIT:60


ability-stat-description:
    # The descriptions for each ability stat.
    STRENGTH: "The physical power of your character."
    STAMINA: "The healthiness of your character."
    AGILITY: "The quickness of your character."
    ENDURANCE: "The cardiovascular longevity of your character."
    INTELLIGENCE: "The smart... ness.. of your character."

# -----------------------------------------------------------------------------
# Warp points that Characters uses for various purposes.
#
# Syntax: <world>,<x>,<y>,<z>
# -----------------------------------------------------------------------------
locations:

    # ---
    # The location players will be in immediately after logging in or switching
    # characters, while their data is being loaded from the database.
    loading-location: valeros,4723,110,5325

    # ---
    # The location players are sent to when they are creating a new character
    create-location: valeros,4723,110,5325

    # ---
    # The location players are sent to when they finish creating their character
    start-location: valeros,4723,110,5325


# -----------------------------------------------------------------------------
# Settings for when a player is considered "in combat"
# -----------------------------------------------------------------------------
combat-status:

    # ---
    # The number of seconds a player has to wait to be out of combat after they deal or take damage
    # to/from a mob or the environment.
    #
    # For example, if 10 seconds and I hit a mob, I would then have to wait 10 seconds after hitting
    # that mob before I could teleport or switch characters. If I hit the mob again in those 10
    # seconds, the timer would be reset to 0.
    seconds-until-out-of-pve: 10

    # ---
    # The same as above, but specifically for damage to/from other players.
    seconds-until-out-of-pvp: 10


# -----------------------------------------------------------------------------
# Configuration for leveling and the experience it takes to level up.
# -----------------------------------------------------------------------------
leveling:

    #---
    # The maximum level that player-characters can be. At this level, when the
    # player is awarded experience, nothing will happen. If the max level is
    # later raised, they will be able to level normally again.
    max-level: 20

    # ---
    # The amount of experience between levels.
    #
    # For example, with "1: 400" it takes 400 experience to get from level 0 to
    # level 1. With "11: 8700" it takes 8700 experience to get from level 10 to 11.
    #
    # Do not leave any gaps.
    xp-to-level:
        1: 400
        2: 900
        3: 1400
        4: 2100
        5: 2800
        6: 3600
        7: 4500
        8: 5400
        9: 6500
        10: 7600
        11: 8700
        12: 9800
        13: 11000
        14: 12300
        15: 13600
        16: 15000
        17: 16400
        18: 17800
        19: 19300
        20: 20800
        21: 22400
        22: 24000
        23: 25500
        24: 27200
        25: 28900
        26: 30500
        27: 32200
        28: 33900
        29: 36300
        30: 38800
        31: 41600
        32: 44600
        33: 48000
        34: 51400
        35: 55000
        36: 58700
        37: 62200
        38: 66200
        39: 70200
        40: 74300
        41: 78500
        42: 82800
        43: 87100
        44: 91600
        45: 96300
        46: 101000
        47: 105800
        48: 110700
        49: 115700
        50: 120900
        51: 126000
        52: 131500
        53: 137000
        54: 142500
        55: 148200
        56: 154000
        57: 159900
        58: 165800
        59: 172000
        60: 290000
