stat-description:
    # The descriptions for each stat.
    MAX_HEALTH: "Dictates how many hits your character can take before dying."
    HEALTH_REGEN: "Determines your healing rate."
    MAX_MANA: "Dictates how many spells your character can cast."
    MANA_REGEN: "Determines your mana regeneration rate."
    MAX_ENERGY: "Dictates how often your character can use abilities."
    ENERGY_REGEN: "Determines your energy regeneration rate."
    SPEED: "Dictates how fast your character can move."
    PHYSICAL_ATTACK: "How hard your character hits."
    MAGIC_ATTACK: "How powerful your magical attacks hit."
    ARMOR: "Determines how much damage is reduced when you take a hit."
    FIRE_RESISTANCE: "Your resistance to general fire damage."
    ICE_RESISTANCE: "Your resistance to general ice damage."
    HIT_CHANCE: "The chance for you to strike an enemy when attacking."
    DODGE_CHANCE: "The chance you will dodge an incoming attack."
    CRIT_CHANCE: "The chance you will do critical damage when successfully striking an enemy."

# -------------------------------------------------------------------------------------------------
# The default combat stats if no other stats are defined. In the vast majority of cases, an
# entity's stats should be specifically designed. However, in cases where they are not, these will
# be used instead.
#
# For a full list of CombatEngine's stats, see:
# https://bitbucket.org/legendsofvaleros/combatengine/src/master/src/main/java/com/legendsofvaleros/combatengine/stat/Stat.java?at=master
# -------------------------------------------------------------------------------------------------
default-combat-profile:
    # The values for each stat. See the stat guide for explanations of these stats and their values.
    MAX_HEALTH: 100
    HEALTH: 100
    HEALTH_REGEN: 100
    MAX_MANA: 100
    MANA: 100
    MANA_REGEN: 100
    MAX_ENERGY: 100
    ENERGY: 100
    ENERGY_REGEN: 100
    SPEED: 100
    PHYSICAL_ATTACK: 100
    MAGIC_ATTACK: 100
    ARMOR: 0
    FIRE_RESISTANCE: 0
    ICE_RESISTANCE: 0
    # Ex: 50.0 HIT_CHANCE is a 50% chance to hit. Same goes for DODGE_CHANCE and CRIT_CHANCE.
    HIT_CHANCE: 90
    DODGE_CHANCE: 5
    CRIT_CHANCE: 5


# -------------------------------------------------------------------------------------------------
# Settings for ARMOR, MAGIC_ATTACK, and PHYSICAL_ATTACK stats as well as elemental resistances.
#
# These settings define how much each of these stats actually affect base damage amounts.
# -------------------------------------------------------------------------------------------------
damage-modifiers:

    offensive:
        # ---
        # The percentage increase in physical damage for each point of the PHYSICAL_ATTACK stat, as
        # a decimal. Ex: 0.01 for 1%, 0.005 for 0.5%, 1.0 for 100%
        #
        # For example, if this was set to 0.001 (0.1%), and an entity had a 95 PHYSICAL_ATTACK stat,
        # the base damage of their physical attacks would be increased by 9.5%.
        physical-multiplier-per-point: 0.001

        # ---
        # The same thing as above, except for spell damage and the MAGIC_ATTACK stat.
        magic-multiplier-per-point: 0.001

    defensive:
        # ---
        # The ARMOR stat defends against both physical and magic damage. You can define here by how
        # much ARMOR reduces damage for each type of damage.
        armor:
            # ---
            # The percentage decrease in physical damage for each point of the ARMOR stat, as a
            # decimal. Ex: 0.01 for 1%, 0.005 for 0.5%, 1.0 for 100%
            #
            # For example, if this was set to 0.001 (0.1%), and an entity had a 197 ARMOR stat,
            # the base damage of physical attacks on them would be reduced by 19.7%.
            physical-reduction-per-point: 0.001

            # ---
            # The same as above, except for defending against spell damage.
            #
            # Because spell damage can also be reduced by elemental resistances, it may be wise for
            # armor to reduce magic damage less than it reduces physical damage.
            magic-reduction-per-point: 0.0007

        # ---
        # Elemental resistances such as FIRE_RESISTANCE and ICE_RESISTANCE reduce damage from specific
        # types of spells.
        resistances:
            # ---
            # The percentage decrease in spell damage for each point in the spell's corresponding
            # resistance stat, as a decimal. Ex: 0.01 for 1%, 0.005 for 0.5%, 1.0 for 100%
            #
            # Elemental resistances only affect one or another type of spell. If a player has 10,000
            # FIRE_RESISTANCE and gets hit with an ice spell, their FIRE_RESISTANCE stat will not affect
            # the base damage in any way.
            damage-reduction-per-point: 0.001


# -------------------------------------------------------------------------------------------------
# Settings for movement speed and slowness debuffs.
# -------------------------------------------------------------------------------------------------
speed-stat:

    # ---
    # The speed stat level at which entities move at their normal speed. TODO is this still valid, or have we made it different for non-player mobs?
    stat-for-normal-speed: 100.0

    # ---
    # The number of speed stat points per speed or slowness potion effect.
    #
    # For example, if normal speed is 100.0, and this is 10.0, an entity with a 90 speed stat will
    # have a Slowness I potion effect and an entity with an 80 speed stat will have a Slowness II
    # potion effect. In this example, an entity with a 110 speed stat would have a Speed I potion
    # effect, and so on.
    #
    # Potion effect levels are always rounded down. In the above example, an entity with a 109.9999
    # speed stat would not have a Speed I potion effect until they got 110 speed or more. The same
    # goes for Slowness, so that in the above example, if an entity had 90.001 speed, they would not
    # have Slowness I until their speed went to 90 or lower.
    points-per-potion-level: 10.0


# -------------------------------------------------------------------------------------------------
# Settings for player respawns.
# -------------------------------------------------------------------------------------------------
player-respawns:

    # ---
    # The percentage of each stat's max that players should respawn with, as a decimal
    # Ex: 0.1 for 10%, 0.5 for 50%, 1.0 for 100%
    health-percentage: 0.5
    mana-percentage: 0.5
    energy-percentage: 0.5


# -------------------------------------------------------------------------------------------------
# Settings for chances for attacks to hit or else be dodged.
#
# Note that some damage cannot be dodged no matter what.
# -------------------------------------------------------------------------------------------------
dodging:

    # ---
    # The chance for damage not caused by an entity to successfully hit (if it does not hit, it
    # is dodged and does no damage).
    #
    # For instance, if a mob walks through fire and takes fire damage from an ambiguous source
    # (not from being attacked by another entity or their skills), what is the chance that that damage
    # will successfully hit and avoid missing? Ex: 0.0 will miss always, 0.5 is 50% chance to hit.
    #
    # IMPORTANT: This number is not absolute on its own. This will be combined with the damaged entity's
    # dodge chance. So, if this is 0.9 for 90% accuracy, and the damaged entity has a 20% chance to dodge,
    # the ultimate chance of a successful hit is 70%. If you want to make sure environmental damage
    # never misses, even damage which has been specifically set to be able to miss, set this to a very
    # high number like 999999.
    environmental-hit-chance: 1.0


# -------------------------------------------------------------------------------------------------
# Settings for critical hit chances and damage bonuses
# -------------------------------------------------------------------------------------------------
critical-hits:

    # ---
    # How much to multiply damage by for a critical hit. Ex: if 2.0, then critical hits will do
    # double damage.
    damage-multiplier: 2.0

    # ---
    # The chance for damage not caused by an entity to be a critical hit.
    #
    # For instance, if a mob walks through fire and takes fire damage from an ambiguous source
    # (not from being attacked by another entity or their skills), what is the chance that that damage
    # can crit? Ex: 0.0 is no chance, 0.5 is 50% chance.
    environmental-crit-chance: 0.0


# -------------------------------------------------------------------------------------------------
# Settings for health, mana, and energy regeneration
# -------------------------------------------------------------------------------------------------
regeneration:

    # ---
    # The amount of time, in seconds, between each regeneration tick. For example, if 5, health
    # would regenerate in small chunks every 5 seconds.
    #
    # The size of the chunk is determined by entities' stats and other settings. This settings just
    # defines how often it happens.
    #
    # WARNING: Changing this can have a very large effect on all regen rates for all entities.
    regen-period-seconds: 5

    # ---
    # This is a complex setting. These values define how much the HEALTH_REGEN, MANA_REGEN, and
    # ENERGY_REGEN stats will cause entities to regenerate their health, mana, and energy.
    #
    # These values are percentages represented as decimals (100% is 1.0, 50% is 0.5, 1% is 0.01) that are
    # multiplied against max health/mana/energy stats and REGEN stats to get the amount of
    # health/mana/energy regenerated each regen period.
    #
    # Here is an example using health: Every X seconds (see above), every entity's health will be
    # restored with the following formula:
    #
    #   max-health * HEALTH_REGEN-stat * percent-of-max-per-health-regen = amount of health restored
    #
    # So, if a player had 1,230 MAX_HEALTH, a 250 HEALTH_REGEN stat, and the health
    # percent-of-max-per-health-regen was set to 0.0001, the resulting health regen per X seconds
    # would be:
    #
    #   1,230 * 250 * 0.0001 = 30.75 health restored every X seconds.
    #
    # In this case, for every point of the HEALTH_REGEN stat the player has, they regenerate 0.01% of
    # their MAX_HEALTH every X seconds. Because they have 250 HEALTH_REGEN, they regenerate 2.5% of their
    # MAX_HEALth every X seconds. 2.5% of 1,230 is 30.75; the player regenerates 30.75 health every X seconds.
    #
    # Mana and energy use the same formula, but using the MAX_MANA/MAX_ENERGY stats and the
    # MANA_REGEN/ENERGY_REGEN stats, respectively.
    percent-of-max-per-regen-stat:
        HEALTH: 0.001
        MANA: 0.001
        ENERGY: 0.001


# -------------------------------------------------------------------------------------------------
# Settings for damage and kill attribution.
# -------------------------------------------------------------------------------------------------
damage-attribution:

    # ---
    # The max distance (in blocks) between entities at which one can get credit for killing the
    # other.
    #
    # For example, if this is 32 and I kill a zombie, I must be within 32 blocks to get credit for
    # the kill. If I kill it with an arrow from 40 blocks away, I will not get credit for the kill.
    max-kill-distance: 32

    # ---
    # How long, in seconds, damage history will be stored for until it is forgotten.
    #
    # For as long as kill-attribution is based solely on who got the last hit, this is purely to avoid
    # memory leaks and should not be changed.
    history-expiration-seconds: 60


# -------------------------------------------------------------------------------------------------
# Settings threat/aggro levels and mob-AI targeting.
# -------------------------------------------------------------------------------------------------
threat:

    # ---
    # The maximum distance between two entities where one can still be threatened by and target the
    # other.
    #
    # For example, if this is 32 and I am being targeted by a mob, if I go more than 32 blocks away,
    # that mob will no longer be threatened by me or target me.
    max-targeting-distance: 32

    # ---
    # The number of seconds it takes for threat to expire in full. Threat will steadily decrease from when
    # it was last generated (when I hit a mob, for example) until this many seconds pass, when it
    # will reach 0. If more threat is added (such as if I attack again), this countdown will be reset.
    #
    # For example, my friend and I are fighting a mob. I hit the mob 5 times and generate 100 threat.
    # This setting is at 15 seconds and after 15 seconds, my threat level is 0. After my threat goes
    # down to 0 after those 15 seconds, if my friend hits the mob even once, the mob will start to
    # attack him because my threat has gone down lower than his over time.
    threat-expiration-seconds: 15
